name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      pull-requests: write
    steps:
      - name: 🛒 Checkout repo
        uses: actions/checkout@v4

      - name: 🧨 Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: 🧨 Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: 📥 Install Dependencies
        run: pnpm install

      - name: 🦋 Changesets
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
